```{r}
## Libraries
library(tidyverse)
# library(purrr)
# library(httr)
# library(magrittr)

library(raster)
library(rgdal)
library(lidR)

library(functional)
library(RColorBrewer)

library(glue)
library(furrr)
# future::plan(multiprocess)
```

```{r}
years <- c(2013,2014)
ws <-c(20)
```

```{r}
dir_data <-"../Data/lidar"

dir_chm <- paste(dir_data,"raster",sep="/")
dir_treetops <- paste(dir_data,"vector","treetops",years,sep="/")

dir_crowns <- paste(dir_data,"raster","crowns",years,sep = "/")
walk(dir_crowns,dir.create)

filename_crowns_index <- paste(dir_data,"raster","crowns","index.txt",sep="/")
filename_crowns_errors <- paste(dir_data,"raster","crowns","errors.txt",sep="/")

```
```{r}
## Read rasters
chm_filenames <- paste0(dir_chm,"/raster",years,".tif")
chms <- map(chm_filenames,raster)
```

```{r}
read_treetops <- function(year,ws){
  filename <-paste0("treetops_lmf_ws",ws,".json")
  filename_full <- paste(dir_data,"vector","treetops",year,filename,sep = "/")
  readOGR(filename_full)
}
```


```{r}
single_run <- function(iYear,ws,th_seed,th_cr,max_cr){
  year <- years[[iYear]]
  r <- chms[[iYear]]
  treetops <-read_treetops(year,ws)
  crowns <-dalponte2016(
    r,
    treetops,
    th_tree = 2,
    th_seed = th_seed,
    th_cr = th_cr,
    max_cr = max_cr,
    ID = "treeID"
  )()
  
  # write GeoTIFF to file and parameters to the index
  filename <- glue("dalponte_{year}_{ws}_seed{th_seed}_cr{th_cr}_max{max_cr}.tif")
  filename_full <- paste(dir_crowns[[iYear]],filename,sep = "/")
  print(filename_full)
  writeRaster(crowns,filename_full,overwrite=T)
}

double_run <- function(ws,th_seed,th_cr,max_cr){
  c(1,2) %>%
    future_map(~single_run(.,ws,th_seed,th_cr,max_cr))%>%
    {.}
  cat(c(ws,th_seed,th_cr,max_cr),"\n",file=filename_crowns_index,append=T)
}
random_run <- function() {
  th_seed=runif(1,min=0.2,max=0.7)
  th_cr=runif(1,min=0.3,max=0.8)
  max_cr=runif(1,min=40,max=70)
  try(
    double_run(ws=ws,
             th_seed=th_seed,
             th_cr=th_cr,
             max_cr = max_cr),
    outFile = filename_crowns_errors
  )
}
```
```{r}

  # dalponte2016(
  #   r,
  #   treetops,
  #   th_tree = 2,
  #   th_seed = 0.45,
  #   th_cr = 0.55,
  #   max_cr = 50,
  #   ID = "treeID"
  # )()
```

```{r}
double_run(ws,0.45,0.55,50)
```

```{r}
library(foreach)
library(doParallel)
cores=detectCores()
cl <- makeCluster(cores[1])
registerDoParallel(cl)

foreach(i=1:200, .combine=cbind) %dopar% {
   functionThatDoesSomething() #calling a function
}
#stop cluster
stopCluster(cl)
```

```{r,fig.width=17,fig.height=16}
```

```{r}
sprintf_transformer <- function(text, envir) {
  m <- regexpr(":.+$", text)
  if (m != -1) {
    format <- substring(regmatches(text, m), 2)
    regmatches(text, m) <- ""
    res <- eval(parse(text = text, keep.source = FALSE), envir)
    do.call(sprintf, list(glue("%{format}f"), res))
  } else {
    eval(parse(text = text, keep.source = FALSE), envir)
  }
}
glue_fmt <- function(..., .envir = parent.frame()) {
  glue(..., .transformer = sprintf_transformer, .envir = .envir)
}
a = 2013
print(paste(a))
print(glue_fmt("{a}"))
```

