```{r}
## Libraries
library(tidyverse)
# library(purrr)
# library(httr)
# library(magrittr)

library(raster)
library(rgdal)
library(spatial)
library(stars)
library(sf)

library(functional)
```

```{r}
years <- c(2013,2014)
```

```{r}

dir_data <-"/home/code/ai4er/mres/Data/lidar/danum"
```
```{r}
dir_chm <- paste(dir_data,"rasters",sep="/")
dir_treetops <- paste(dir_data,"treetops",years,sep="/")

dir_crowns <- paste(dir_data,"crowns",sep = "/")
dir_crowns_r <- paste(dir_crowns,"raster",years,sep = "/")
dir_crowns_v <- paste(dir_crowns,"vector",years,sep = "/")

walk(dir_crowns,dir.create)

filename_crowns_index <- paste(dir_data,"index.txt",sep="/")
filename_crowns_errors <- paste(dir_data,"errors.txt",sep="/")

```


```{r}

read_treetops <- function(year,ws){
  filename <-paste0("treetops_lmf_ws",ws,".json")
  filename_full <- paste(dir_treetops,year,filename,sep = "/")
  readOGR(filename_full)
}
read_crowns <- function(alg_name){
  filename <-paste0("2013_18_",alg_name,".shp")
  filename_full <- paste(dir_crowns,"vector","old",filename,sep = "/")
  readOGR(filename_full)
}
```

```{r}
## Read rasters
chm_filenames <- paste0(dir_chm,"/raster",years,".tif")
chms <- map(chm_filenames,raster)
```

```{r}
tt18 <- read_treetops(2013,18)
cro_s <- read_crowns('silva')
cro_d <- read_crowns('dalponte')
```

```{r}
plot(cro_s)
plot(cr,add=T)
plot(tt,add=T,cex=1.3)
```


```{r,fig.width=8,fig.height=7.45}

# Plot Silva
ex <- chms[[1]]@extent
n <- 5
ex <- extent(ex@xmin+2*(ex@xmax-ex@xmin)/n, ex@xmin+3*(ex@xmax-ex@xmin)/n,
             ex@ymin+2*(ex@ymax-ex@ymin)/n, ex@ymin+3*(ex@ymax-ex@ymin)/n)
# tt = crop(tt18,ex)
# crs = crop(cro_s,ex)
r <- crop(chms[[1]], ex)
plot(r,legend.shrink=0.8,legend.width=2)
plot(cro_s,add=T)
plot(tt18,add=T,col='red')
# axis.args=list(cex.axi)
# set.colorbar(cex=1.5)
```

```{r,fig.width=8,fig.height=7.45}

# Plot Dalponte
ex <- chms[[1]]@extent
n <- 5
ex <- extent(ex@xmin+2*(ex@xmax-ex@xmin)/n, ex@xmin+3*(ex@xmax-ex@xmin)/n,
             ex@ymin+2*(ex@ymax-ex@ymin)/n, ex@ymin+3*(ex@ymax-ex@ymin)/n)
# tt = crop(tt18,ex)
# crs = crop(cro_s,ex)
r <- crop(chms[[1]], ex)
plot(r,legend.shrink=0.8,legend.width=2)
plot(cro_d,add=T)
plot(tt18,add=T,col='red')
# axis.args=list(cex.axi)
# set.colorbar(cex=1.5)
```

